/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

/**
 *
 * @author USUARIO
 */
public class Ejercicio_1 extends javax.swing.JFrame {
    
    DefaultTableModel mt1 = new DefaultTableModel();
    DefaultTableModel mt2 = new DefaultTableModel();
    DefaultTableModel mt3 = new DefaultTableModel();

    /**
     * Creates new form Ejercicio_1
     */
    public Ejercicio_1() {
        initComponents();
        
        //Configurar modelo tabla 1 mt1
        String ids1 [] = {"Clase", "Miami", "Madrid"};
        mt1.setColumnIdentifiers(ids1);
        tablaDestinoClases.setModel(mt1);
        
        //Agregar filas mt1
        agregarFilaTablaDestino(mt1,"Primera", 1300000, 2700000);
        agregarFilaTablaDestino(mt1,"Segunda", 1120000, 2500000);
        agregarFilaTablaDestino(mt1,"Tercera", 1100000, 2320000);
        
        //Configurar modelo tabla 2 mt2
        String ids2 [] = {"Rango","Descuento"};
        mt2.setColumnIdentifiers(ids2);
        tablaDescuentosCantPasajes.setModel(mt2);
        
        //Agregar filas mt2
        agregarFilaTablaDescuento(mt2, "3 - 5", "2.6 %" );
        agregarFilaTablaDescuento(mt2, "6 - 10", "5.38 %" );
        agregarFilaTablaDescuento(mt2, "11 y mas", "7.24 %" );
        
        //configurar model tabla 3 mt3
        String ids3 [] = {"Tipo Viaje", "Descuento"};
        mt3.setColumnIdentifiers(ids3);
        tablaDescuentoTipoViaje.setModel(mt3);
        
        //Agregar filas mt3
        addRowTableTipoViaje(mt3, "Familiar", "7 %");
        addRowTableTipoViaje(mt3, "Turistico", "4.75 %");

        
    }
    
    private void agregarFilaTablaDestino(DefaultTableModel modeloTabla, String clase, int cantidad1, int cantidad2){
        NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance(new Locale("es" , "CO"));
        Object [] fila = {clase, formatoMoneda.format(cantidad1), formatoMoneda.format(cantidad2),};
        mt1.addRow(fila);
    }
    
    private void agregarFilaTablaDescuento(DefaultTableModel modeloTabla, String cantPasajes, String porcentaje){
        Object [] fila = {cantPasajes, porcentaje};
        mt2.addRow(fila);
    }
    
    private void addRowTableTipoViaje(DefaultTableModel modeloTabla, String tipoViaje, String Descuento){
        Object [] fila = {tipoViaje, Descuento};
        mt3.addRow(fila);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDestinoClases = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTipoViaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtClase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumPasajeros = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDescuentosCantPasajes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaDescuentoTipoViaje = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Ejercicio # 1");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Vientos AIR");

        tablaDestinoClases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tablaDestinoClases);

        jLabel3.setText("Nombre:");

        jLabel4.setText("Destino:");

        jLabel5.setText("Clase:");

        txtClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaseActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de viaje:");

        jLabel7.setText("Numero de pasajes:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        tablaDescuentosCantPasajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(tablaDescuentosCantPasajes);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Descuentos por cantidad de pasajes");

        jLabel9.setText("Cedula:");

        tablaDescuentoTipoViaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(tablaDescuentoTipoViaje);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Descuentos por tipo de viaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(322, 322, 322)
                                .addComponent(jLabel8)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(169, 169, 169)
                                        .addComponent(btnAceptar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6))
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtClase, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                                    .addComponent(txtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                                    .addComponent(txtTipoViaje, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                                    .addComponent(txtCedula)
                                                    .addComponent(txtNumPasajeros))))))
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(btnAceptar)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaseActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String nombre = txtNombre.getText();
        String destino = txtDestino.getText();
        String clase = txtClase.getText();
        String tipoViaje = txtTipoViaje.getText();
        String cedula = txtCedula.getText();
        int cantPasajes = Integer.parseInt(txtNumPasajeros.getText());
        
        long totalSinDescuento = calcularPrecio(destino, clase, cantPasajes);
        double totalConDescuentoTipoViaje = descuentoTipoViaje(tipoViaje, totalSinDescuento);
        double totalTodosLosDescuentos = descuentoCantPasajes( totalSinDescuento, cantPasajes);
        double total = totalSinDescuento - (totalConDescuentoTipoViaje + totalTodosLosDescuentos);
        
        
        StringBuilder mensaje = new StringBuilder();
        NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance(new Locale("es" , "CO"));
        
        mensaje.append("Estimado cliente: " + nombre + "\n");
        mensaje.append("Documento ID: " + cedula + "\n"); 
        mensaje.append("Cantidad pasajes: " + cantPasajes + "\n"); 
        mensaje.append("Total a pagar : " + formatoMoneda.format(total) + "\n\n");
        
        
        if (tipoViaje.equalsIgnoreCase("familiar")) {
            mensaje.append("Su descuento por tipo de viaje familiar fue de 7 %" + "\n");
            mensaje.append("Valor descuento: " + formatoMoneda.format(totalConDescuentoTipoViaje) + "\n");
        } else if(tipoViaje.equalsIgnoreCase("turistico")){
            mensaje.append("Su descuento por tipo de viaje turistico fue de 4.75 %" + "\n");
            mensaje.append("Valor descuento: " + formatoMoneda.format(totalConDescuentoTipoViaje) + "\n");

        }
        
        if (cantPasajes >= 3 && cantPasajes <= 5) {
            mensaje.append("Su descuento por comprar de 3 a 5 pasajes fue de 2.6 %" + "\n");
            mensaje.append("Valor descuento: " + formatoMoneda.format(totalTodosLosDescuentos) + "\n");

        } else if(cantPasajes >= 6 && cantPasajes <= 10){
            mensaje.append("Su descuento por comprar de 6 a 10 pasajes fue de 5.38 %" + "\n");
            mensaje.append("Valor descuento: " + formatoMoneda.format(totalTodosLosDescuentos) + "\n");
        } else if(cantPasajes >= 11){
            mensaje.append("Su descuento por comprar 11 o mas pasajes fue de 7.24 %" + "\n");
            mensaje.append("Valor descuento: " + formatoMoneda.format(totalTodosLosDescuentos) + "\n");
        }
        
        
        result.setText(mensaje.toString());
        
        txtNombre.setText("");
        txtDestino.setText("");
        txtClase.setText("");
        txtTipoViaje.setText("");
        txtCedula.setText("");
        txtNumPasajeros.setText("");
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    public long calcularPrecio ( String destino, String clase, int cantPasajes){
        
        long total = 0;
        
        if(destino.toLowerCase().contains("miami")){
            
            switch (clase.toLowerCase()) {
                case "primera":
                    total = cantPasajes * 1300000;
                    break;
                case "segunda":
                    total = cantPasajes * 1120000;
                    break;
                case "tercera":
                    total = cantPasajes * 1100000;
                    break;
                default:
                    break;
            }
        }  else if(destino.toLowerCase().contains("madrid")){
            
            switch (clase.toLowerCase()){
                case "primera":
                    total = cantPasajes * 2700000;
                    break;
                case "segunda":
                    total = cantPasajes * 2500000;
                    break;
                case "tercera":
                    total = cantPasajes * 2320000;
                    break;
                default:
                    break;
            }
        }
        
        return total;
    }
    
    public double descuentoTipoViaje(String tipoDeViaje, long subTotal){
        
        double total = 0;
        
        switch (tipoDeViaje.toLowerCase()){
            case "familiar":
                total = subTotal * 0.07;
                break;
            case "turistico":
                total= subTotal * 0.0475;
                break;
            default:
                break;
        }
        return total;
    }
    
    public double descuentoCantPasajes(long totalSinDescuento, int cantPasaje){
        double total = 0;
        
        if (cantPasaje >= 3 && cantPasaje <=5){
            total = totalSinDescuento * 0.026;
        } else if (cantPasaje >= 6 && cantPasaje <=10){
             total = totalSinDescuento * 0.0538;
        } else if (cantPasaje > 11){
             total = totalSinDescuento * 0.0724;
        }
        
        return total;
    }
    
    
    /*public void calcularDescuento (String tipoViaje, String clase, String destino, int cantPasajes){
        StringBuilder resultado = new StringBuilder();
        double infoPrecio;
        String infoFinal;
        
        if("primera".equals(clase) && "miami".equals(destino)){
            long precioPasajeMiamiPrimera = 1300000 * cantPasajes;
           
            if("familiar".equals(tipoViaje)){
                infoPrecio = precioPasajeMiamiPrimera - (precioPasajeMiamiPrimera * 0.07) ;
                
                if(cantPasajes >=3 && cantPasajes<=5){
                    infoPrecio = infoPrecio - (infoPrecio * 0.026);
                    
                    resultado.append("Su precio total a pagar es de: " + infoPrecio + "\n" + 
                             "ya que obtuvo un descuento del 7% por ser su viaje de tipo familiar y un descuento\n"+
                             " del 2.6% por comprar de 3 a 5 pasajes");
                    result.setText(resultado.toString());
                    
                }else if(cantPasajes >=6 && cantPasajes<=10){
                    infoPrecio = infoPrecio - (infoPrecio * 0.0538);
                    
                    resultado.append("Su precio total a pagar es de: " + infoPrecio + "\n" + 
                             "ya que obtuvo un descuento del 7% por ser su viaje de tipo familiar y un descuento\n"+
                             " del 5.38% por comprar de 6 a 10 pasajes");
                    result.setText(resultado.toString());
                    
                }else if(cantPasajes >=11){
                    infoPrecio = infoPrecio - (infoPrecio * 0.0724);
                    
                    resultado.append("Su precio total a pagar es de: " + infoPrecio + "\n" + 
                             "ya que obtuvo un descuento del 7% por ser su viaje de tipo familiar y un descuento\n"+
                             " del 7.24% por comprar 11 pasajes en adelante.");
                    result.setText(resultado.toString());
                }
                else{
                    resultado.append("Su precio total a pagar es de: " + infoPrecio + "\n" + 
                             "ya que obtuvo un descuento del 7% por ser su viaje de tipo familiar y un descuento\n");
                    result.setText(resultado.toString());
                }       
            }
            else if("turistico".equals(tipoViaje)){
                infoPrecio = precioPasajeMiamiPrimera * 0.0475 ;
            }
            else{
                
            }
            
        }
        else if("segunda".equals(clase) && "miami".equals(destino)){
            long precioPasajeMiamiSegunda = 1120000 * cantPasajes;
            
        }
        else if("tercera".equals(clase) && "miami".equals(destino)){
            long precioPasajeMiamiTercera = 1100000 * cantPasajes;
        }
        else if("primera".equals(clase) && "madrid".equals(destino)){
            long precioPasajeMadridPrimera = 2700000 * cantPasajes;
        }
        else if("segunda".equals(clase) && "madrid".equals(destino)){
            long precioPasajeMadridSegunda = 2500000 * cantPasajes;
        }
        else if("tercera".equals(clase) && "madrid".equals(destino)){
            long precioPasajeMadridTercera = 2320000 * cantPasajes;
        }
        
        
        
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea result;
    private javax.swing.JTable tablaDescuentoTipoViaje;
    private javax.swing.JTable tablaDescuentosCantPasajes;
    private javax.swing.JTable tablaDestinoClases;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtClase;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumPasajeros;
    private javax.swing.JTextField txtTipoViaje;
    // End of variables declaration//GEN-END:variables
}
