/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Ejercicio_4 extends javax.swing.JFrame {
    
    DefaultTableModel mt1 = new DefaultTableModel();

    /**
     * Creates new form Ejercicio_4
     */
    public Ejercicio_4() {
        initComponents();
        
        String titulos [] = {"Estrato", "Nivel de consumo", "Tarifa basica"};
        mt1.setColumnIdentifiers(titulos);
        tabla.setModel(mt1);
        
        addRows(mt1, "1", "<= 10", "$ 5.000");
        addRows(mt1, "2", "<= 25", "$ 10.000");
        addRows(mt1, "3", "<= 35", "$ 15.000");
        addRows(mt1, "4", "<= 40", "$ 20.000");
       
    }

    public void addRows(DefaultTableModel modeTable, String estrato, String consumo, String tarifa){
        Object fila [] ={estrato, consumo, tarifa};
        mt1.addRow(fila);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        consumo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        estrato = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Ejercicio 4");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese el consumo regristrado:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese el estrato:");

        result.setColumns(20);
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(consumo)
                                    .addComponent(estrato, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(aceptar)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(estrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static final int TARIFA_EXCESO = 800;
    public static final int TARIFA_ESTRATO_1 = 5000;
    public static final int TARIFA_ESTRATO_2 = 10000;
    public static final int TARIFA_ESTRATO_3 = 15000;
    public static final int TARIFA_ESTRATO_4 = 20000;

    
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        int consu = Integer.parseInt(consumo.getText());
        int estrat = Integer.parseInt(estrato.getText());
        
        
        StringBuilder cadena = new StringBuilder();
        NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));
        
        if(estrat == 1){
            
            if(consu <= 10){

                cadena.append("Su consumo fue de: ").append(consu).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(TARIFA_ESTRATO_1)).append("\n");

            } else if(estrat == 1 && consu > 10){
                int subTotal = consu - 10;
                int valorExceso = subTotal * TARIFA_EXCESO;
                int total = TARIFA_ESTRATO_1 + (subTotal * TARIFA_EXCESO);
                cadena.append("Su consumo superó el tope, tendrá un recargo de $ 800 \n" 
                        + "por cada punto adicional\n\n");
                cadena.append("Puntos de Exceso: ").append(subTotal).append("\n");
                cadena.append("Valor exceso: ").append(formatoMoneda.format(valorExceso)).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(total)).append("\n");
            }
            
        } else if(estrat == 2){
            
            if(consu <= 25){

                cadena.append("Su consumo fue de: ").append(consu).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(TARIFA_ESTRATO_2)).append("\n");

            } else if(estrat == 2 && consu > 25){
                int subTotal = consu - 25;
                int valorExceso = subTotal * TARIFA_EXCESO;
                int total = TARIFA_ESTRATO_2 + (subTotal * TARIFA_EXCESO);
                cadena.append("Su consumo superó el tope, tendrá un recargo de $ 800 \n" 
                        + "por cada punto adicional\n\n");
                cadena.append("Puntos de Exceso: ").append(subTotal).append("\n");
                cadena.append("Valor exceso: ").append(formatoMoneda.format(valorExceso)).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(total)).append("\n");
            }
            
        } else if(estrat == 3){
            if(consu <= 35){

                cadena.append("Su consumo fue de: ").append(consu).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(TARIFA_ESTRATO_3)).append("\n");

            } else if(estrat == 3 && consu > 35){
                int subTotal = consu - 35;
                int valorExceso = subTotal * TARIFA_EXCESO;
                int total = TARIFA_ESTRATO_3 + (subTotal * TARIFA_EXCESO);
                cadena.append("Su consumo superó el tope, tendrá un recargo de $ 800 \n" 
                        + "por cada punto adicional\n\n");
                cadena.append("Puntos de Exceso: ").append(subTotal).append("\n");
                cadena.append("Valor exceso: ").append(formatoMoneda.format(valorExceso)).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(total)).append("\n");
            }
        
        } else if(estrat == 4){
            if(consu <= 40){

                cadena.append("Su consumo fue de: ").append(consu).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(TARIFA_ESTRATO_4)).append("\n");

            } else if(estrat == 4 && consu > 40){
                int subTotal = consu - 40;
                int valorExceso = subTotal * TARIFA_EXCESO;
                int total = TARIFA_ESTRATO_4 + (subTotal * TARIFA_EXCESO);
                cadena.append("Su consumo superó el tope, tendrá un recargo de $ 800 \n" 
                        + "por cada punto adicional\n\n");
                cadena.append("Puntos de Exceso: ").append(subTotal).append("\n");
                cadena.append("Valor exceso: ").append(formatoMoneda.format(valorExceso)).append("\n");
                cadena.append("Total a pagar: ").append(formatoMoneda.format(total)).append("\n");
            }
        
        } else {
            cadena.append("Escriba un estrato valido");
        }
        
        result.setText(cadena.toString());
    }//GEN-LAST:event_aceptarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField consumo;
    private javax.swing.JTextField estrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea result;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
