/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Ejercicio_5 extends javax.swing.JFrame {
    
    DefaultTableModel mt1 = new DefaultTableModel();
    DefaultTableModel mt2 = new DefaultTableModel();

    /**
     * Creates new form Ejercicio_5
     */
    public Ejercicio_5() {
        initComponents();
        
        String titulo1 [] = {"Codigo", "Tipo", "Valor matricula"};
        mt1.setColumnIdentifiers(titulo1);
        tablaCarreras.setModel(mt1);
        
        addRowsTableCarreras(mt1, "1", "Profesional", "$ 300.000");
        addRowsTableCarreras(mt1, "2", "Tecnología", "$ 150.000");
        addRowsTableCarreras(mt1, "3", "Técnico profesional", "$ 100.000");
        
        String titulo2 [] = {"Codigo", "Tipo", "Porc. Recargo"};
        mt2.setColumnIdentifiers(titulo2);
        tablaDesc.setModel(mt2);
        
        addRowsTableDesc(mt2, "1", "Diurna", "5 %");
        addRowsTableDesc(mt2, "2", "Nocturna", "10 %");
        
    }
    
    public void addRowsTableCarreras(DefaultTableModel modeloTabla, String codigo, String tipo, String valorMatricula){
        Object fila [] = {codigo, tipo, valorMatricula};
        mt1.addRow(fila);
    }
    
    public void addRowsTableDesc(DefaultTableModel modeloTabla, String codigo, String tipo, String porcRecargo){
        Object fila [] = {codigo, tipo, porcRecargo};
        mt2.addRow(fila);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarreras = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDesc = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codeStud = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Ejercicio 5");

        tablaCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tablaCarreras);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Descuentos");

        tablaDesc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tablaDesc);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Valor Carreras");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese el codigo del estudiante:");

        result.setColumns(20);
        result.setRows(5);
        jScrollPane3.setViewportView(result);

        aceptar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(205, 205, 205))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(codeStud, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(aceptar)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codeStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String code = codeStud.getText();
        int valorCarrera = 0;
        double valorDesJornada;
        double descJornada;
        double total;
        
        StringBuilder cadena = new StringBuilder();
        NumberFormat formatMoneda = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));
        
        if(code.length() == 5){
            int num = Integer.parseInt(code);
            
            int tresUltimos =num % 1000;
            num /= 1000;
            int seguDigito = num % 10;
            num /= 10;
            int primDigito = num % 10;
            
            switch(primDigito){
                case 1:
                    valorCarrera = 300000;
                    cadena.append("Tipo carrera: ").append("Profesional\n");
                    cadena.append("Valor carrera: ").append(formatMoneda.format(valorCarrera) + "\n");
                    break;
                case 2:
                     valorCarrera = 150000;
                    cadena.append("Tipo carrera: ").append("Tecnología\n");
                    cadena.append("Valor carrera: ").append(formatMoneda.format(valorCarrera) + "\n");
                    break;
                case 3:
                     valorCarrera = 100000;
                    cadena.append("Tipo carrera: ").append("Técnico profesional\n");
                    cadena.append("Valor carrera: ").append(formatMoneda.format(valorCarrera) + "\n");
                    break;
                default:
                    break;
            }
            
            int consecutivo = tresUltimos % 2;
            
            switch(seguDigito){
                case 1:
                    descJornada = 0.05;
                    valorDesJornada = descJornada * valorCarrera;
                    
                    cadena.append("Su jornada sera Diurna\n");
                    cadena.append("Valor Descuento Jornada: ").append(formatMoneda.format(valorDesJornada)).append("\n");
                    cadena.append("su consecutivo es: ").append(tresUltimos +"\n\n");
                    
                    if(consecutivo == 0){
                        cadena.append("Su consecutivo es par y tiene 20% de descuento adicional\n")
                              .append("Valor descuento: ").append(formatMoneda.format(valorCarrera * 0.2)).append("\n\n");
                        total = valorCarrera - (valorCarrera * (descJornada + 0.2));
                        cadena.append("Total a pagar: ").append(formatMoneda.format(total));
                        
                    } else {
                        cadena.append("Su consecutivo es impar y tiene 10% de descuento adicional\n")
                              .append("Valor descuento: ").append(formatMoneda.format(valorCarrera * 0.1)).append("\n\n");
                        total = valorCarrera - (valorCarrera * (descJornada + 0.1));
                        cadena.append("Total a pagar: ").append(formatMoneda.format(total));
                    }
                    
                    break;
                    
                case 2:
                    descJornada = 0.1;
                    valorDesJornada = descJornada * valorCarrera;
                    
                    cadena.append("Su jornada sera Nocturna\n");
                    cadena.append("Valor Descuento Jornada: ").append(formatMoneda.format(valorDesJornada)).append("\n");
                    cadena.append("su consecutivo es: ").append(tresUltimos +"\n\n");
                    
                     if(consecutivo == 0){
                        cadena.append("Su consecutivo es par y tiene 20% de descuento adicional\n")
                              .append("Valor descuento: ").append(formatMoneda.format(valorCarrera * 0.2)).append("\n\n");
                        total = valorCarrera - (valorCarrera * (descJornada + 0.2));
                        cadena.append("Total a pagar: ").append(formatMoneda.format(total));
                    } else {
                         cadena.append("Su consecutivo es impar y tiene 10% de descuento adicional\n")
                              .append("Valor descuento: ").append(formatMoneda.format(valorCarrera * 0.1)).append("\n\n");
                        total = valorCarrera - (valorCarrera * (descJornada + 0.1));
                        cadena.append("Total a pagar: ").append(formatMoneda.format(total));
                    }
                    
                    break;
                default:
                    break;
            }
            
        } else {
            cadena.append("Escriba un codigo de 5 digitos");
        }
        
        result.setText(cadena.toString());
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField codeStud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea result;
    private javax.swing.JTable tablaCarreras;
    private javax.swing.JTable tablaDesc;
    // End of variables declaration//GEN-END:variables
}
