/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Currency;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Ejercicio_8 extends javax.swing.JFrame {
    DefaultTableModel mt1 = new DefaultTableModel();
    

    /**
     * Creates new form Ejercicio_8
     */
    public Ejercicio_8() {
        initComponents();
        
        String ids [] = {"Numero pelota", "Color pelota"};
        mt1.setColumnIdentifiers(ids);
        tabla.setModel(mt1);
        
        addRow(mt1, "1", "Roja");
        addRow(mt1, "2", "Amarilla");
        addRow(mt1, "3", "Verde");
        
    }

    public void addRow(DefaultTableModel modelTabla, String numero, String color){
        Object fila [] = {numero, color};
        mt1.addRow(fila);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pelota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Ejercicio 8");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Escriba el valor de su compra: ");

        aceptar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Si su compra es mayor a $ 50.000 obtendra descuento");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        result.setColumns(20);
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Bolsa de pelotas");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Escriba el numero de su pelota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(293, 293, 293)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(13, 13, 13)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pelota, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(numero))
                                .addGap(77, 77, 77)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pelota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(aceptar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        int num = Integer.parseInt(numero.getText());
        
        double descuento = 0;
        double descPelota = 0;
        double total;
        
        StringBuilder cadena = new StringBuilder();
        NumberFormat formatoMoneda = new DecimalFormat("$#,##0");
        formatoMoneda.setCurrency(Currency.getInstance(new Locale("es", "CO")));
         //NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));
        
        
        
        if(num > 50000){
            
            String numeroPelota = pelota.getText();
            
            if(numeroPelota.isEmpty()){
                cadena.append("Debes elegir un numero de pelota para continuar");
            } else {
                
                int numPelota = Integer.parseInt(numeroPelota);
                double valorIva = num * 0.16;
                double vlDescPorMayorCincuentaMil = valorIva * 0.05;
                double totalIvaConDescuento = valorIva - vlDescPorMayorCincuentaMil;
                switch (numPelota) {
                    case 1:
                        descuento = 0.1;
                        descPelota = num * 0.1;
                       
                        System.out.println(descPelota);
                        cadena.append("Su pelota roja le da un descuento de 10% sobre el valor de la compra\n")
                                .append("valor descuento pelota: ").append(formatoMoneda.format(descPelota)).append("\n")
                                .append("valor de 16 % de IVA sin descuento: ").append(formatoMoneda.format(valorIva)).append("\n")
                                .append("valor para compras mayores a 50.000 descuento de 5% de IVA:  ").append(formatoMoneda.format(vlDescPorMayorCincuentaMil)).append("\n")
                                .append("valor total a pagar de IVA:  ").append(formatoMoneda.format(totalIvaConDescuento)).append("\n");
                        break;
                    case 2:
                        descuento = 0.15;
                        descPelota = num * 0.15;
                        cadena.append("Su pelota amarilla le da un descuento de 15% sobre el valor de la compra\n")
                                .append("valor descuento pelota: ").append(formatoMoneda.format(descPelota )).append("\n")
                                .append("valor de 16% de IVA sin descuento: ").append(formatoMoneda.format(valorIva)).append("\n")
                                 .append("valor para compras mayores a 50.000 descuento de 5% de IVA:  ").append(formatoMoneda.format(vlDescPorMayorCincuentaMil)).append("\n")
                                .append("valor total a pagar de IVA:  ").append(formatoMoneda.format(totalIvaConDescuento)).append("\n");
                        break;
                    case 3:
                        descuento = 0.2;
                        descPelota = num * 0.2;
                        cadena.append("Su pelota verde le da un descuento de 20% sobre el valor de la compra\n")
                                .append("valor descuento pelota: ").append(formatoMoneda.format(descPelota)).append("\n")
                                .append("valor de 16% de IVA sin descuento: ").append(formatoMoneda.format(valorIva)).append("\n")
                                 .append("valor para compras mayores a 50.000 descuento de 5% de IVA:  ").append(formatoMoneda.format(vlDescPorMayorCincuentaMil)).append("\n")
                                .append("valor total a pagar de IVA:  ").append(formatoMoneda.format(totalIvaConDescuento)).append("\n");
                        break;
                    default:
                        cadena.append("Escribe un numero de pelota valido\n");
                        break;
                }

                total = (num - descPelota) + totalIvaConDescuento;
                cadena.append("Total a pagar: ").append(formatoMoneda.format(total));
            }
            
        } else {
            total = num +(num * 0.16);
            cadena.append("Se le cobró un 16 % de IVA\n")
                  .append("Total a pagar: ").append(formatoMoneda.format(total));
          
        }
          result.setText(cadena.toString());
       
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pelota;
    private javax.swing.JTextArea result;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
